import { Geist, Geist_Mono, Nunito } from "next/font/google";
import './defaults.css';
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        {children}
      </body>
    </html>
  );
}
